### PR TITLE
DI-321 - GRCh38 TWE conductor config 2.0.0

### PR DESCRIPTION
**Pull request by Addy81**
Update conductor config for TWE to use resources for GRCh38. 

Files included in this config:

```
grep -oE 'file-[A-Za-z0-9]+' eggd_conductor_dias_TWE_config_v2.0.0.json   | xargs -P8 -n1 -I{} dx describe --json {} | jq -c '[.id,.name]'

["file-Gb76f204XGybZ3J6F731xkBp","GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18_noChr.bwa-index.tar.gz"]
["file-G7YKFZj4kj47GxgQ2bKGYV1g","Omni25_genotypes_1525_samples_v2.b38.PASS.ALL.sites_no_chr.vcf.gz"]
["file-F3zvKp84fXX8qJx43zZXP395","GRCh38.gatk.resource.bundle.tar.gz"]
["file-Gb772VQ4XGyzQ0Zk615XbZ0X","GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18_noChr.fasta-index.tar.gz"]
["file-G7FK1xQ4kj4317YGFpqYPb75","Twist_ComprehensiveExome_targets_hg38_noChr_2020-09.bed"]
["file-GPQX4G04x14XV5PFfqGkGJk1","somalier_v0.2.16.tar.gz"]
["file-Gb757784XGyY3FPvkPQ74K9z","GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18_noChr.fasta.gz"]
["file-GZYqkkQ4fPQpKYz0BYPZk68j","GCF_000001405.39_GRCh38.p13_genomic.exon_5bp.tsv"]
["file-G7FJjz04kj424vq826gKbZx7","sites.hg38.nochr.vcf"]
["file-GYv4kJj43bPFv25JX1ZP7Z39","HG001_GRCh38_1_22_v4.2.1_benchmark_noChr.bed"]
["file-GYv4kKQ43bP9XZZXz7bYJJjx","HG001_GRCh38_1_22_v4.2.1_benchmark_noChr.vcf.gz"]
["file-GFGbK48433GzV4y54b25p43Z","pkrusche_happy_v0.3.9.tar.gz"]
["file-Gb772VQ4XGyzQ0Zk615XbZ0X","GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18_noChr.fasta-index.tar.gz"]
["file-Gb75X184XGypG6k0fq8P6Y6Z","GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18_noChr.sdf.tar"]
["file-GbYg9J04XGyqK7xkQjbXj6GG","panelapp_GMS_transcripts_b38_v1.0.0.bed"]
["file-Gb772VQ4XGyzQ0Zk615XbZ0X","GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18_noChr.fasta-index.tar.gz"]
["file-GV8KZp04FfpQ7JPzzBbGXX2x","WES_multiqc_config_v2.1.0.yaml"]
["file-GPQX4G04x14XV5PFfqGkGJk1","somalier_v0.2.16.tar.gz"]
["file-GFGbK48433Gk4xYG8KK05QqY","ga4gh_rep.py_v1.0.tar.gz"]
["file-GF3PxgQ433Gqv1Q029Gjzjfv","seglh_multiqc_v1.11.tar.gz"]

```

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Addy81)

___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 21 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-Nlcw5VR3fsfPAmOcKST:-Nlcw5VR3fsfPAmOcKSU:b4b9yoy) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L21)):*
> ```JSON
>     },
>     "executables": {
>         "workflow-GbXF3bQ4zbvBzjg4j6884z3g": {
> ```

Checked



_Code quote:_
```JSON
workflow-GbXF3bQ4zbvBzjg4j6884z3g
```
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 38 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NlcwELFBEgnqJARHT9Z:-NlcwELGB5V6JswSTzwh:b4b9yoy) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L38)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-Gb757784XGyY3FPvkPQ74K9z"
> ```

Checked



_Code quote:_
```JSON
file-Gb757784XGyY3FPvkPQ74K9z
```
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 44 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NlcwOVV4Kxqa_nCWtCw:-NlcwOVV4Kxqa_nCWtCx:b4b9yoy) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L44)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-Gb76f204XGybZ3J6F731xkBp"
> ```

Checked



_Code quote:_
```JSON
file-Gb76f204XGybZ3J6F731xkBp
```
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 50 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NlcwbPfB2e7LWs8K5AE:-NlcwbPfB2e7LWs8K5AF:b4b9yoy) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L50)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-F3zqGV04fXX5j7566869fjFq",
>                         "id": "file-F3zvKp84fXX8qJx43zZXP395"
> ```

Checked



_Code quote:_
```JSON
file-F3zvKp84fXX8qJx43zZXP395
```
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 56 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NlcwkbB6ozNpUYFwv8i:-NlcwkbB6ozNpUYFwv8j:b4b9yoy) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L56)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-G7YKFZj4kj47GxgQ2bKGYV1g"
> ```

Checked



_Code quote:_
```JSON
file-G7YKFZj4kj47GxgQ2bKGYV1g
```
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 62 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NldNCJXE2yudR3Lzi46:-NldNCJZ2Gh-dACwxUen:b4b9yoy) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L62)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-GZYqkkQ4fPQpKYz0BYPZk68j"
> ```

Checked



_Code quote:_
```JSON
file-GZYqkkQ4fPQpKYz0BYPZk68j
```
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 71 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NldNL6d8NrIfas0Dwqs:-NldNL6e9KQKhmWVCz7a:b4b9yoy) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L71)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-Gb772VQ4XGyzQ0Zk615XbZ0X"
> ```

Checked



_Code quote:_
```JSON
file-Gb772VQ4XGyzQ0Zk615XbZ0X
```
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 77 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NldNTaYDMVKC-mb9uBM:-NldNTaYDMVKC-mb9uBN:b-75kfnl) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L77)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-G7FK1xQ4kj4317YGFpqYPb75"
> ```

file-G7FK1xQ4kj4317YGFpqYPb75



_Code quote:_
```JSON
file-G7FK1xQ4kj4317YGFpqYPb75
```
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 89 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NldNcJL6bTq0VaUaHS6:-NldNcJM8oEqDzSOiKKV:b4b9yoy) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L89)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-Gb772VQ4XGyzQ0Zk615XbZ0X"
> ```

Checked



_Code quote:_
```JSON
file-Gb772VQ4XGyzQ0Zk615XbZ0X
```
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 95 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NldNifg2-um1NxLCNPj:-NldNifg2-um1NxLCNPk:b4b9yoy) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L95)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-G7FJjz04kj424vq826gKbZx7"
> ```

Checked



_Code quote:_
```JSON
file-G7FJjz04kj424vq826gKbZx7
```
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 110 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NldNrlgDMJ7Bi_gpZCt:-NldNrlgDMJ7Bi_gpZCu:b4b9yoy) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L110)):*
> ```JSON
>             }
>         },
>         "workflow-GZFB75j4kYX4k6jfG3f9p3XX": {
> ```

Checked



_Code quote:_
```JSON
workflow-GZFB75j4kYX4k6jfG3f9p3XX
```
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 134 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NldNzEE8T-4T9i1pI_6:-NldNzEE8T-4T9i1pI_7:bsjxz11) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L134)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-GYv4kKQ43bP9XZZXz7bYJJjx"
> ```

Switch to HG002



_Code quote:_
```JSON
file-GYv4kKQ43bP9XZZXz7bYJJjx
```
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 140 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NldOLEr5BLK9R1UvMyH:-NldOLEs9zDLBJ5w7040:b4b9yoy) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L140)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-GbYg9J04XGyqK7xkQjbXj6GG"
> ```

Checked



_Code quote:_
```JSON
file-GbYg9J04XGyqK7xkQjbXj6GG
```
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 146 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NldOSPoEIwyrX9e8gCG:-NldOSPpBm3xSJTsdnI1:bsjxz11) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L146)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-GYv4kJj43bPFv25JX1ZP7Z39"
> ```

Switch to HG002



_Code quote:_
```JSON
file-GYv4kJj43bPFv25JX1ZP7Z39
```
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 152 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NldOZN42tYQyJ28pTB-:-NldOZN42tYQyJ28pTB0:b4b9yoy) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L152)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-Gb772VQ4XGyzQ0Zk615XbZ0X"
> ```

Checked



_Code quote:_
```JSON
file-Gb772VQ4XGyzQ0Zk615XbZ0X
```
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 158 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NldOf1UCHsxjTfig5Sv:-NldOf1UCHsxjTfig5Sw:b4b9yoy) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L158)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-Gb75X184XGypG6k0fq8P6Y6Z"
> ```

Checked



_Code quote:_
```JSON
file-Gb75X184XGypG6k0fq8P6Y6Z
```

**Review by Addy81 — COMMENTED** [review]
I realise we should probably decide on new hap.py thresholds. Not sure if you want to sign off as is then update the threshold in the next update (with HG002?)

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-:-Nm15CAsE4fLKzoFQdJC:bvmks4i)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @mattgarner)

___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 134 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NldNzEE8T-4T9i1pI_6:-Nm14mc37P3OB6Qgrwe2:b-odnqmp) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L134)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Switch to HG002
</blockquote></details>

Decided to do this in next version to allow easier retrospective processing of runs
___
*[`assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json` line 146 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32#-NldOSPoEIwyrX9e8gCG:-Nm14tU15Tt3EKyS-xxX:b-odnqmp) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7ca86315b8542b6d3844d762e9c313aec6023f47/assay_configs/TWE/eggd_conductor_dias_TWE_config_v2.0.0.json#L146)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Switch to HG002
</blockquote></details>

Decided to do this in next version to allow easier retrospective processing of runs

**Comment by Addy81** [comment]
File id for this file: file-GZXYkVj4X7kpZbYZJZPXgFkJ

Used in : https://platform.dnanexus.com/panx/projects/Gf063Vj4vB5GpvyYpBXxvQQP/monitor/job/Gf06V6Q4vB51p029zY23BQ8b

**Review by mattgarner — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/32)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Addy81)

**Comment by Addy81** [comment]
To ensure no disruption from any b37 updates, the latest signed-off b37 config was re-added into the repo. 

`dx download project-Fkb6Gkj433GVVvj73J7x8KbV:file-GYKz8Vj4zbz2VGYxVgxv787y
git add eggd_conductor_dias_TWE_config_v1.1.1.json `

**Pull request merged**
