### PR TITLE
Update to latest ClinVar

### PR DESCRIPTION
**Pull request by growland2**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/28)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/28)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @growland2)

___
*[`assay_configs/MYE/eggd_conductor_uranus_MYE_config_v1.2.4.json` line 13 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/28#-Njs8QR7B4qMOW_bA7L0:-Njs8QR7B4qMOW_bA7L1:bqv8z6j) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/91092d7646624f90e1332c1f53d74cbff4b6a2f6/assay_configs/MYE/eggd_conductor_uranus_MYE_config_v1.2.4.json#L13)):*
> ```JSON
>         "v1.2.1": "Added the new EPIC procedure code to end of assay_code field",
>         "v1.2.3": "Updated to use latest ClinVar and COSMIC annotation resource",
>         "v1.2.4": "Updated to use latest ClinVar annotation resource"
> ```

can you add the version from the file name into the changelog please



_Code quote:_
```JSON
latest ClinVar annotation resource
```

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/28)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @growland2)

**Review by growland2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/28)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`assay_configs/MYE/eggd_conductor_uranus_MYE_config_v1.2.4.json` line 13 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/28#-Njs8QR7B4qMOW_bA7L0:-NjvJjCkDHmiuXM34Y-f:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/91092d7646624f90e1332c1f53d74cbff4b6a2f6/assay_configs/MYE/eggd_conductor_uranus_MYE_config_v1.2.4.json#L13)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you add the version from the file name into the changelog please
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/28)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @growland2)

**Pull request merged**
