### PR TITLE
updated dias_single to v2.4.0

### PR DESCRIPTION
**Pull request by pofuoku**
- Dias single
  - increment version from 2.1.0 to 2.4.0
  - updated Workflow ID to `workflow-GkKxPz844Vg961YzVyy17Pq2`

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/52)

### CODE REVIEW

**Review by chrispyatt — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/52)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pofuoku)

___
*[`assay_configs/CEN/eggd_conductor_dias_CEN_config_v1.4.0.json` line 20 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/52#-NzTlr-CDELLtnmFwNiz:-NzTlr-D1CHMaAEnKB6B:bmf6c2o) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7f9be24175de23b1c73c1b409297d2782d9c76ff/assay_configs/CEN/eggd_conductor_dias_CEN_config_v1.4.0.json#L20)):*
> ```JSON
>     },
>     "executables": {
>         " workflow-GkKxPz844Vg961YzVyy17Pq2": {
> ```

extra space before workflow ID

**Review by chrispyatt — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/52)* status: all files reviewed, 1 unresolved discussion (waiting on @pofuoku)

**Review by chrispyatt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/52)* status: all files reviewed, 1 unresolved discussion (waiting on @pofuoku)

**Review by pofuoku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/52)* status: all files reviewed, 1 unresolved discussion

___
*[`assay_configs/CEN/eggd_conductor_dias_CEN_config_v1.4.0.json` line 20 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/52#-NzTlr-CDELLtnmFwNiz:-NzgemCQ24tTBPG_j7ou:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/7f9be24175de23b1c73c1b409297d2782d9c76ff/assay_configs/CEN/eggd_conductor_dias_CEN_config_v1.4.0.json#L20)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

extra space before workflow ID
</blockquote></details>

Done.

**Pull request merged**
