### PR TITLE
Updates all reference genome files to b38

### PR DESCRIPTION
**Pull request by growland2**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/31)

### CODE REVIEW

**Comment by Addy81** [comment]
Reference genome files need to be in 001 and project-ids updated before this can be signed off.

**Comment by mattgarner** [comment]
Ref genome files now in 001, project-ids can be updated

**Comment by mattgarner** [comment]
HG002 for hap.py please

**Comment by growland2** [comment]
Conductor job was run on one sample using the dev config file and successfully completed (job link: [job-Gf07VYQ4vB54G84VJ9YYkvyq](https://platform.dnanexus.com/panx/projects/Gf063Vj4vB5GpvyYpBXxvQQP/monitor/job/Gf07VYQ4vB54G84VJ9YYkvyq))

**Review by Addy81 — CHANGES_REQUESTED** [review]
Workflows checked ok, all but one file as expected.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/31#-:-NnF20FA8VikVgmIeCHE:bc6lv22)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @growland2)

___
*[`assay_configs/CEN/eggd_conductor_dias_CEN_config_v2.0.0.json` line 60 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/31#-NnF0qnP-E_C8xYsYW9b:-NnF0qnQ7lROXRLKYUih:bdp2u3v) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/a5bcc1a7c58ffe0dbac19b3eeb74a947ecd88062/assay_configs/CEN/eggd_conductor_dias_CEN_config_v2.0.0.json#L60)):*
> ```JSON
>                     "$dnanexus_link": {
>                         "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>                         "id": "file-GFF77q84kj4J701y0Gq3KqqV"
> ```

This needs to be replaced with GCF_000001405.39_GRCh38.p13_genomic.exon_5bp.tsv  file-GZYqkkQ4fPQpKYz0BYPZk68j

**Review by Addy81 — APPROVED** [review]
Workflows checked ok. 

All files are 38 as expected:

```
adriana@WorkAT:~/Projects$ grep -oE 'file-[A-Za-z0-9]+' ~/Downloads/eggd_conductor_dias_CEN_config_v2.0.0.json   | xargs -P8 -n1 -I{} dx describe --json {} | jq -c '[.id,.name]'
["file-Gb757784XGyY3FPvkPQ74K9z","GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18_noChr.fasta.gz"]
["file-GP2bGp848QggjG456FJ1vG95","CEN_regions_captured_grch38_v1.0.0.bed"]
["file-GPQX4G04x14XV5PFfqGkGJk1","somalier_v0.2.16.tar.gz"]
["file-GZYqkkQ4fPQpKYz0BYPZk68j","GCF_000001405.39_GRCh38.p13_genomic.exon_5bp.tsv"]
["file-G7YKFZj4kj47GxgQ2bKGYV1g","Omni25_genotypes_1525_samples_v2.b38.PASS.ALL.sites_no_chr.vcf.gz"]
["file-Gb772VQ4XGyzQ0Zk615XbZ0X","GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18_noChr.fasta-index.tar.gz"]
["file-F3zvKp84fXX8qJx43zZXP395","GRCh38.gatk.resource.bundle.tar.gz"]
["file-Gb76f204XGybZ3J6F731xkBp","GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18_noChr.bwa-index.tar.gz"]
["file-G7FJjz04kj424vq826gKbZx7","sites.hg38.nochr.vcf"]
["file-GYv4kKQ43bP9XZZXz7bYJJjx","HG001_GRCh38_1_22_v4.2.1_benchmark_noChr.vcf.gz"]
["file-Gb772VQ4XGyzQ0Zk615XbZ0X","GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18_noChr.fasta-index.tar.gz"]
["file-Gf0265j4XGyVZgV9VkG615xf","CEN_genes_b38_v1.0.0.bed"]
["file-Gb772VQ4XGyzQ0Zk615XbZ0X","GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18_noChr.fasta-index.tar.gz"]
["file-GFGbK48433GzV4y54b25p43Z","pkrusche_happy_v0.3.9.tar.gz"]
["file-GYv4kJj43bPFv25JX1ZP7Z39","HG001_GRCh38_1_22_v4.2.1_benchmark_noChr.bed"]
["file-Gb75X184XGypG6k0fq8P6Y6Z","GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18_noChr.sdf.tar"]
["file-GFGbK48433Gk4xYG8KK05QqY","ga4gh_rep.py_v1.0.tar.gz"]
["file-GF3PxgQ433Gqv1Q029Gjzjfv","seglh_multiqc_v1.11.tar.gz"]
["file-GPQX4G04x14XV5PFfqGkGJk1","somalier_v0.2.16.tar.gz"]
["file-GV55qpj47f086YFQb47B5Gg4","CEN_multiqc_config_v2.1.0.yaml"]
```

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/31#-:-NnFMVZ6DEID0fpK0laP:bit2too)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @growland2)

___
*[`assay_configs/CEN/eggd_conductor_dias_CEN_config_v2.0.0.json` line 60 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/31#-NnF0qnP-E_C8xYsYW9b:-NnFM0G3AvrISSD0giAL:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/a5bcc1a7c58ffe0dbac19b3eeb74a947ecd88062/assay_configs/CEN/eggd_conductor_dias_CEN_config_v2.0.0.json#L60)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

This needs to be replaced with GCF_000001405.39_GRCh38.p13_genomic.exon_5bp.tsv  file-GZYqkkQ4fPQpKYz0BYPZk68j
</blockquote></details>

Done

**Pull request merged**
