### PR TITLE
v1.2.8

### PR DESCRIPTION
**Pull request by growland2**
update to latest clinvar, fix issue #23

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/37)

### CODE REVIEW

**Review by woook — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/37)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @growland2)

___
*[`assay_configs/MYE/eggd_conductor_uranus_MYE_config_v1.2.8.json` line 0 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/37#gh-1500580363:-NrL8fBC882r6nULJA-N:b-tkxxtg) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/d5a1db2698da4196fce23d424c9992e759c5d3c4/assay_configs/MYE/eggd_conductor_uranus_MYE_config_v1.2.8.json#L0)):*
<details><summary><i>Previously, growland2 wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/eastgenomics/eggd_conductor_configs/pull/37#discussion_r1500580363) to the right spot — sorry!)*

Identical file in 001 Ref used instead ```
$ diff -s <(dx cat file-FyFGvzQ41zgBq7xf4Gy9Q28g) <(
dx cat file-G00jqQj4J7Byv963KkZ40kXv)
Files /dev/fd/63 and /dev/fd/62 are identical
```
```

</blockquote></details>

Why are there two identical files?

**Review by growland2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/37)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @woook)

___
*[`assay_configs/MYE/eggd_conductor_uranus_MYE_config_v1.2.8.json` line 0 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/37#gh-1500580363:-NrLD2p79tpHRVJ3BviJ:b4rfp3e) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/d5a1db2698da4196fce23d424c9992e759c5d3c4/assay_configs/MYE/eggd_conductor_uranus_MYE_config_v1.2.8.json#L0)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Why are there two identical files?
</blockquote></details>

The file referenced in prior version (v1.2.7) was project-G21BGP84q5JFYf168QjZ58Vz:file-G00jqQj4J7Byv963KkZ40kXv - which is a 003 project - see issue description [here](https://github.com/eastgenomics/eggd_conductor_configs/issues/23), I have now changed this to reference the copy of this file in 001 Ref i.e. project-Fkb6Gkj433GVVvj73J7x8KbV:file-FyFGvzQ41zgBq7xf4Gy9Q28g , and the diff statement was to demonstrate that the updated referenced file is identical to the old one (i.e. file-G00jqQj4J7Byv963KkZ40kXv = file-G00jqQj4J7Byv963KkZ40kXv). Apologies, should have added more context.

**Review by woook — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/37)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @growland2)

___
*[`assay_configs/MYE/eggd_conductor_uranus_MYE_config_v1.2.8.json` line 0 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/37#gh-1500580363:-NrLgWfC8Q-HMuRqeWll:b-bg907m) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/d5a1db2698da4196fce23d424c9992e759c5d3c4/assay_configs/MYE/eggd_conductor_uranus_MYE_config_v1.2.8.json#L0)):*
<details><summary><i>Previously, growland2 wrote…</i></summary><blockquote>

The file referenced in prior version (v1.2.7) was project-G21BGP84q5JFYf168QjZ58Vz:file-G00jqQj4J7Byv963KkZ40kXv - which is a 003 project - see issue description [here](https://github.com/eastgenomics/eggd_conductor_configs/issues/23), I have now changed this to reference the copy of this file in 001 Ref i.e. project-Fkb6Gkj433GVVvj73J7x8KbV:file-FyFGvzQ41zgBq7xf4Gy9Q28g , and the diff statement was to demonstrate that the updated referenced file is identical to the old one (i.e. file-G00jqQj4J7Byv963KkZ40kXv = file-G00jqQj4J7Byv963KkZ40kXv). Apologies, should have added more context.
</blockquote></details>

Agree that we don't want to reference a 003 project file.
Is it sufficient to document the diff you have done in this PR alone? Is it in confluence?
Did you consider moving the file that was being used to 001?
Is the copy in 001 used elsewhere?
Is the copy in 003 used elsewhere?

**Review by growland2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/37)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @woook)

___
*[`assay_configs/MYE/eggd_conductor_uranus_MYE_config_v1.2.8.json` line 0 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/37#gh-1500580363:-NrZTVoG1VWDGEXGg1K8:b-r5b2a3) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/d5a1db2698da4196fce23d424c9992e759c5d3c4/assay_configs/MYE/eggd_conductor_uranus_MYE_config_v1.2.8.json#L0)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Agree that we don't want to reference a 003 project file.
Is it sufficient to document the diff you have done in this PR alone? Is it in confluence?
Did you consider moving the file that was being used to 001?
Is the copy in 001 used elsewhere?
Is the copy in 003 used elsewhere?
</blockquote></details>

This change is described in the "changes" section of the testing doc.

Moving the file which was being used to 001 seems wrong as then you would have duplicate files in 001.

Searching our repos on GitHub, the 001 file (file-FyFGvzQ41zgBq7xf4Gy9Q28g) is used elsewhere - see search results [here](https://github.com/search?q=org%3Aeastgenomics+file-FyFGvzQ41zgBq7xf4Gy9Q28g&type=code). 

The 003 file (file-G00jqQj4J7Byv963KkZ40kXv) is referenced in only one other repo in Github, being set as the default reference genome index in the [eggd_cgppindel dxapp.json](https://github.com/eastgenomics/eggd_cgppindel/blob/d60221c230ee9c367efe8935787d852234bd6657/dxapp.json#L51-L52). I can create an issue for this in the eggd_cgppindel repo as was done for this one.

**Review by growland2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/37)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @woook)

___
*[`assay_configs/MYE/eggd_conductor_uranus_MYE_config_v1.2.8.json` line 0 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/37#gh-1500580363:-NrZZFtG0CgqBNNGCIaX:b-1rqelc) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/d5a1db2698da4196fce23d424c9992e759c5d3c4/assay_configs/MYE/eggd_conductor_uranus_MYE_config_v1.2.8.json#L0)):*
<details><summary><i>Previously, growland2 wrote…</i></summary><blockquote>

This change is described in the "changes" section of the testing doc.

Moving the file which was being used to 001 seems wrong as then you would have duplicate files in 001.

Searching our repos on GitHub, the 001 file (file-FyFGvzQ41zgBq7xf4Gy9Q28g) is used elsewhere - see search results [here](https://github.com/search?q=org%3Aeastgenomics+file-FyFGvzQ41zgBq7xf4Gy9Q28g&type=code). 

The 003 file (file-G00jqQj4J7Byv963KkZ40kXv) is referenced in only one other repo in Github, being set as the default reference genome index in the [eggd_cgppindel dxapp.json](https://github.com/eastgenomics/eggd_cgppindel/blob/d60221c230ee9c367efe8935787d852234bd6657/dxapp.json#L51-L52). I can create an issue for this in the eggd_cgppindel repo as was done for this one.
</blockquote></details>

Edit: The diff command will be evidenced under the testing section in the testing doc.

**Pull request merged**
