### PR TITLE
TSO500_v1.2.0

### PR DESCRIPTION
**Pull request by Arun-bioinformatics**
renamed:    assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.1.0.json -> assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.2.0.json
    Added eggd_metricsoutput_editor onto the assay_config file, testing of the app can be found here:
    https://cuhbioinformatics.atlassian.net/wiki/spaces/DV/pages/3120365600/eggd+MetricsOutput+editor+v1.0.0

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/39)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/39)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Arun-bioinformatics)

___
*[`assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.2.0.json` line 11 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/39#-Nswl9eq9A1seE0Gkr21:-Nswl9eq9A1seE0Gkr22:bsnefaa) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/9e2628277ecb2d6deda6ed9cb26682e79c0c50d4/assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.2.0.json#L11)):*
> ```JSON
>         "v1.0.1": "Add new Epic procedure codes to assay_code field",
>         "v1.1.0": "Update eggd_TSO500 v1.2.0 -> v2.0.0",
>         "v1.2.0": "Add eggd_metricsoutput_editor after the effect of eggd_TSO500"
> ```

not sure this reads quite right, did you mean something like `to run after eggd_TSO500`?



_Code quote:_
```JSON
 after the effect of 
```

**Review by Arun-bioinformatics — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/39)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.2.0.json` line 11 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/39#-Nswl9eq9A1seE0Gkr21:-NswlnB5DZZkICP4k3ZW:b2nign6) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/9e2628277ecb2d6deda6ed9cb26682e79c0c50d4/assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.2.0.json#L11)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

not sure this reads quite right, did you mean something like `to run after eggd_TSO500`?
</blockquote></details>

yes

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/39)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Arun-bioinformatics)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/39#-:-Nt1J3vb4ehl06b1ZHmb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Arun-bioinformatics)

**Pull request merged**
