### PR TITLE
URA-672 TSO v2.0.0

### PR DESCRIPTION
**Pull request by Jay-Miles**
Summary

- The release of Conductor v1.4.0 enables the automated launch of eggd_TSO500_reports_workflow from the output of eggd_tso500. This requires an update to the reports workflow and the Conductor TSO500 config.
- This update is linked to the eggd_TSO500_reports_workflow v2.0.0 testing at https://cuhbioinformatics.atlassian.net/wiki/spaces/DV/pages/3189244398/eggd+TSO500+reports+workflow+v2.0.0. 

 Changes

- File renamed with new version
- ‘version’ and ‘changelog’ fields updated with new version
- 'details' field updated as automation now covers entire pipeline
- New parameter “hold“:true added to eggd_tso500 analysis
- Other Helios analyses added to Conductor config:
  - multi_fastqc
  - reports workflow
  - multiQC 
- Changed 'name' field of each analysis to be app(let)/workflow name and version
- Updated with new reports workflow ID

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/47)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
- has this update got a new vep config? is this the correct one since I'm not 100% on latest cancer changes happening
- was there something changing with the MANE annotation app / transcript list or has this been done / am I imagining it?
- are the changes for the transcript sorting fixed / incorporated into this?

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/47#-:-NxNxD7o76fHrl_3A62k:bc6inwf)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @Jay-Miles)

___
*[`assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json` line 156 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/47#-NxNwX4y7Tg2P6xPWkMl:-NxNwX4y7Tg2P6xPWkMm:brbzqgw) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/349c52bbe055d411eca76bfd1b06ce1193c6d345/assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json#L156)):*
> ```JSON
>                 },
>                 "stage-generate_variant_workbook.additional_files": "eggd_tso500.cvo",
>                 "stage-generate_variant_workbook.exclude_columns": "ID CSQ_Allele CSQ_Mastermind_MMID3",
> ```

did you intentionally remove `DP_FMT`?



_Code quote:_
```JSON
 "stage-generate_variant_workbook.exclude_columns": "ID CSQ_Allele CSQ_Mastermind_MMID3",
```
___
*[`assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json` line 157 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/47#-NxNvhcy248cPrHgID5d:-NxNvhczAvpeOksdf25v:b-w1z687) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/349c52bbe055d411eca76bfd1b06ce1193c6d345/assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json#L157)):*
> ```JSON
>                 "stage-generate_variant_workbook.additional_files": "eggd_tso500.cvo",
>                 "stage-generate_variant_workbook.exclude_columns": "ID CSQ_Allele CSQ_Mastermind_MMID3",
>                 "stage-generate_variant_workbook.reorder_columns": "CSQ_SYMBOL CSQ_Consequence CSQ_Feature MANE DNA Protein VF Classification Comment rawChange CHROM POS REF ALT FILTER QUAL DP DP_FMT oncoKB PeCan cBioPortal CSQ_EXON CSQ_INTRON CSQ_IMPACT  CSQ_CADD_PHRED CSQ_REVEL CSQ_gnomADe_AF CSQ_gnomADg_AF CSQ_ClinVar CSQ_ClinVar_CLNSIG CSQ_ClinVar_CLNDN CSQ_SpliceAI_pred_DS_AG CSQ_SpliceAI_pred_DS_AL CSQ_SpliceAI_pred_DS_DG CSQ_SpliceAI_pred_DS_DL CSQ_SpliceAI_pred_DP_AG CSQ_SpliceAI_pred_DP_AL CSQ_SpliceAI_pred_DP_DG CSQ_SpliceAI_pred_DP_DL",
> ```

in here vs the [v2.0.0 workflow PR](https://github.com/eastgenomics/eggd_TSO500_reports_workflow/pull/31/files), it looks like `MANE` and `CSQ_EXON` have moved, and `DP_FMT` has been added after `DP`. Is this the intended changes?




_Code quote:_
```JSON
"CSQ_SYMBOL CSQ_Consequence CSQ_Feature MANE DNA Protein VF Classification Comment rawChange CHROM POS REF ALT FILTER QUAL DP DP_FMT oncoKB PeCan cBioPortal CSQ_EXON CSQ_INTRON CSQ_IMPACT  CSQ_CADD_PHRED CSQ_REVEL CSQ_gnomADe_AF CSQ_gnomADg_AF CSQ_ClinVar CSQ_ClinVar_CLNSIG CSQ_ClinVar_CLNDN CSQ_SpliceAI_pred_DS_AG CSQ_SpliceAI_pred_DS_AL CSQ_SpliceAI_pred_DS_DG CSQ_SpliceAI_pred_DS_DL CSQ_SpliceAI_pred_DP_AG CSQ_SpliceAI_pred_DP_AL CSQ_SpliceAI_pred_DP_DG CSQ_SpliceAI_pred_DP_DL"
```
___
*[`assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json` line 164 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/47#-NxNwKGN6lu-L41v1IS-:-NxNwKGN6lu-L41v1IS0:bs31qqv) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/349c52bbe055d411eca76bfd1b06ce1193c6d345/assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json#L164)):*
> ```JSON
>                 "stage-generate_variant_workbook.add_classification_column": true,
>                 "stage-generate_variant_workbook.add_raw_change": true,
>                 "stage-generate_variant_workbook.freeze_column": "H2",
> ```

has this intentionally changed from I2 to H2? (again from what was removed from workflow PR)



_Code quote:_
```JSON
"H2"
```

**Comment by Jay-Miles** [comment]
*[`assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json` line 156 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/47#-NxNwX4y7Tg2P6xPWkMl:-Ny0czIi5PHU0JsCc7TT:b5hqdtu) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/349c52bbe055d411eca76bfd1b06ce1193c6d345/assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json#L156)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

did you intentionally remove `DP_FMT`?
</blockquote></details>

Yes, it's identical to the DP column, so there was a decision to drop DP_FMT as unnecessary.

**Comment by Jay-Miles** [comment]
*[`assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json` line 156 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/47#-NxNwX4y7Tg2P6xPWkMl:-Ny0idz10K03l7euQ8Kp:bg8fc8o) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/349c52bbe055d411eca76bfd1b06ce1193c6d345/assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json#L156)):*
<details><summary><i>Previously, Jay-Miles wrote…</i></summary><blockquote>

Yes, it's identical to the DP column, so there was a decision to drop DP_FMT as unnecessary.
</blockquote></details>

...ignore this, I think it should be there after all

**Comment by Jay-Miles** [comment]
*[`assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json` line 157 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/47#-NxNvhcy248cPrHgID5d:-Ny0jXZz1-doyATRVNC3:b-ro11x3) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/349c52bbe055d411eca76bfd1b06ce1193c6d345/assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json#L157)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

in here vs the [v2.0.0 workflow PR](https://github.com/eastgenomics/eggd_TSO500_reports_workflow/pull/31/files), it looks like `MANE` and `CSQ_EXON` have moved, and `DP_FMT` has been added after `DP`. Is this the intended changes?

</blockquote></details>

Yep you were right about this, have updated

**Comment by Jay-Miles** [comment]
- Yes, this is the most recent VEP config
- It is using the most recently released versions of everything, or it least it was when I made the PR
- I'm not sure what changes for transcript sorting you mean? The workbooks produced now include '.sorted' in the filename, so possibly

**Comment by Jay-Miles** [comment]
*[`assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json` line 164 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/47#-NxNwKGN6lu-L41v1IS-:-Ny0lVV6-v3rnLzglL0M:bn3psqs) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/349c52bbe055d411eca76bfd1b06ce1193c6d345/assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json#L164)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

has this intentionally changed from I2 to H2? (again from what was removed from workflow PR)
</blockquote></details>

Checked this with Catherine and the last frozen column should be 'Comment', so H2 is right

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/47)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Jay-Miles)

___
*[`assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json` line 156 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/47#-NxNwX4y7Tg2P6xPWkMl:-Ny0n7QI7mRoogzP0KAH:bx76se6) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/349c52bbe055d411eca76bfd1b06ce1193c6d345/assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json#L156)):*
<details><summary><i>Previously, Jay-Miles wrote…</i></summary><blockquote>

...ignore this, I think it should be there after all
</blockquote></details>

so is it being excluded or kept in?

**Comment by Jay-Miles** [comment]
*[`assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json` line 156 at r2](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/47#-NxNwX4y7Tg2P6xPWkMl:-Ny0nf63BSc4wcWuY1q2:b867pe1) ([raw file](https://github.com/eastgenomics/eggd_conductor_configs/blob/349c52bbe055d411eca76bfd1b06ce1193c6d345/assay_configs/TSO500/eggd_conductor_helios_TSO500_config_v1.3.0.json#L156)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

so is it being excluded or kept in?
</blockquote></details>

It should be in the list of columns to exclude

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor_configs/47)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Jay-Miles)

**Pull request merged**
